---
- name: apt cache update
  apt: update_cache=yes

- name: install base packages
  apt: state=latest name=$item update_cache=yes
  with_items:
  - zsh
  - vim
  - git
  - htop
  - iftop
  - mtr-tiny
  - dnsutils
  - screen
  - sudo
  - wget
  - curl
  - rsync
  - build-essential
  - python
  - python-setuptools
  - python-dev
  - python-pip

