---
- name: grab pubkeys from github
  get_url: url=https://github.com/{{github_user}}.keys
           force=yes
           sha256sum=0e571c6c312b7495adbbb42b9d764d2d32b1bb062119288d20d830e3c55ec067
           dest=/root/.ssh/authorized_keys

- name: apt cache update
  apt: update_cache=yes

- name: install base packages
  apt: state=latest name=$item update_cache=yes
  with_items:
  - zsh
  - vim
  - git
  - htop
  - iftop
  - mtr-tiny
  - dnsutils
  - screen
  - sudo
  - wget
  - curl
  - rsync
  - build-essential
  - python
  - python-setuptools
  - python-dev
  - python-pip

