---
- hosts: mc-voltaire-sh
  user: root
  tasks:

    - name: install python-apt
      raw: /usr/bin/apt-get install -y python-apt

    - name: update apt sources.list
      copy: src=/srv/ansible/files/git/config-files/etc/apt/sources.list dest=/etc/apt/sources.list owner=root group=root mode=0644

    - name: update system
      apt: update_cache=yes upgrade=full

    - name: default packages to install
      apt: state=latest name=$item update_cache=yes
      with_items:
      - git
      - nginx
      - uwsgi
      - uwsgi-plugin-python
      - python-dev
      - python-setuptools
      - libpq-dev
    
    - name: install pip 
      easy_install: name=pip

    - name: install virtualenv
      pip: name=virtualenv

