---
- hosts: mc-voltaire-sh
  user: root

  tasks:
    - name: copy over uwsgi configuration
      copy: src=/srv/ansible/files/git/config-files/etc/uwsgi/apps-available/mc-voltaire-sh.ini dest=/etc/uwsgi/apps-available/mc-voltaire-sh.ini owner=www-data group=www-data mode=0644

    - name: uwsgi default.ini
      copy: src=/srv/ansible/files/git/config-files/etc/uwsgi/default.ini dest=/usr/share/uwsgi/conf/default.ini owner=root group=root mode=0644

    - name: symlink to enable uwsgi configuration
      file: src=/etc/uwsgi/apps-available/mc-voltaire-sh.ini dest=/etc/uwsgi/apps-enabled/mc-voltaire-sh.ini owner=www-data group=www-data state=link

    - name: default debian nginx directories suck (sites-avail)
      file: path=/etc/nginx/sites-available state=absent

    - name: default debian nginx directories suck (sites-enabled)
      file: path=/etc/nginx/sites-enabled state=absent

    - name: default debian nginx directories suck (conf.d)
      file: path=/etc/nginx/conf.d state=absent

    - name: create tab-friendly site configuration directories (enable-sites)
      file: path=/etc/nginx/enable-sites state=directory

    - name: create tab-friendly site configuration directories (avail-sites)
      file: path=/etc/nginx/avail-sites state=directory

    - name: copy over nginx server configuration
      copy: src=/srv/ansible/files/git/config-files/etc/nginx/nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=0644

    - name: copy over site nginx configuration
      copy: src=/srv/ansible/files/git/config-files/etc/nginx/enable-sites/mc-voltaire-sh.conf dest=/etc/nginx/enable-sites/mc-voltaire-sh.conf owner=root group=root mode=0644

