---
- hosts: mc-voltaire-sh
  user: root

  tasks:
    - name: copy over uwsgi configuration
      copy: src=/srv/ansible/files/git/config-files/etc/uwsgi/apps-available/mc-voltaire-sh.ini dest=/etc/uwsgi/apps-available/mc-voltaire-sh.ini owner=www-data group=www-data mode=0644

    - name: uwsgi default.ini
      copy: src=/srv/ansible/files/git/config-files/etc/uwsgi/default.ini dest=/usr/share/uwsgi/conf/default.ini owner=root group=root mode=0644

    - name: symlink to enable uwsgi configuration
      file: src=/etc/uwsgi/apps-available/mc-voltaire-sh.conf dest=/etc/uwsgi/apps-enabled/mc-voltaire-sh.conf owner=www-data group=www-data state=link

