---
- hosts: mc-voltaire-sh
  user: root

  tasks:
    - name: create site directory
      file: path=/srv/www/ owner=www-data group=www-data state=directory

    - name: git clone site
      git: repo=git://github.com/voltaire/minecraft-site.git dest=/srv/www/mc-voltaire-sh
    
    - name: pip install requirements
      pip: requirements=/srv/www/mc-voltaire-sh/requirements.txt virtualenv=/srv/www/mc-voltaire-sh/application/env

    - name: config.py
      file: src=/srv/ansible/files/git/config-files/srv/www/mc-voltaire-sh/application/config.py dest=/srv/www/mc-voltaire-sh/application/config.py user=www-data group=www-data mode=0644

