---
- hosts: all
  user: root
  tasks:


    - name: default packages to install
      apt: state=latest name=$item update_cache=yes
      with_items:
      - zsh
      - vim
      - git
      - htop
      - iftop
      - mtr-tiny
      - dnsutils
      - screen
      - sudo
      - wget
      - curl
      - rsync
      - build-essential
      - python
      - python-setuptools
      - python-dev
      - python-pip
    
