---
- name: update system
  apt: update_cache=yes upgrade=full
  notify: install webserver packages

- name: install pip
  easy_install: name=pip

- name: install virtualenv
  pip: name=virtualenv

- name: copy over uwsgi configuration
  copy: src=mc-uwsgi.ini dest=/etc/uwsgi/apps-available/mc-voltaire-sh.ini owner=www-data group=www-data mode=0644

- name: uwsgi default.ini
  copy: src=uwsgi.ini dest=/usr/share/uwsgi/conf/default.ini owner=root group=root mode=0644

- name: symlink to enable uwsgi configuration
  file: src=/etc/uwsgi/apps-available/mc-voltaire-sh.ini dest=/etc/uwsgi/apps-enabled/mc-voltaire-sh.ini owner=www-data group=www-data state=link

- name: default debian nginx directories suck (sites-avail)
  file: path=/etc/nginx/sites-available state=absent

- name: default debian nginx directories suck (sites-enabled)
  file: path=/etc/nginx/sites-enabled state=absent

- name: default debian nginx directories suck (conf.d)
  file: path=/etc/nginx/conf.d state=absent

- name: create tab-friendly site configuration directories (enable-sites)
  file: path=/etc/nginx/enable-sites state=directory

- name: create tab-friendly site configuration directories (avail-sites)
  file: path=/etc/nginx/avail-sites state=directory

- name: copy over nginx server configuration
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=0644

- name: copy over site nginx configuration
  copy: src=nginx-vhost.conf dest=/etc/nginx/enable-sites/mc-voltaire-sh.conf owner=root group=root mode=0644

- name: create site directory
  file: path=/srv/www/ owner=www-data group=www-data state=directory

- name: git clone site
  git: repo=git://github.com/voltaire/minecraft-site.git dest=/srv/www/mc-voltaire-sh

- name: pip install requirements
  pip: requirements=/srv/www/mc-voltaire-sh/requirements.txt virtualenv=/srv/www/mc-voltaire-sh/application/env

- name: config.py
  copy: src=flask-config.py dest=/srv/www/mc-voltaire-sh/application/config.py owner=www-data group=www-data mode=0644

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: restart uwsgi
  service: name=uwsgi state=restarted enabled=yes

