---
- name: install puppetmaster
  apt: state=latest name=puppetmaster update_cache=yes

- name: run puppet
  command: /usr/bin/puppet resource service puppet ensure=running enable=true

- name: run puppetmaster
  command: /usr/bin/puppet resource service puppetmaster ensure=running enable=true

