---
- hosts: all
  user: root
  include: tasks/createuser.yml new_user=jchen
  include: tasks/updatesystem.yml
  include: tasks/basepkgs.yml


- hosts: mc-voltaire-sh
  user: root
  include: tasks/mc-voltaire-sh/basepkgs.yml
  include: tasks/mc-voltaire-sh/configure.yml
  include: tasks/mc-voltaire-sh/init-site.yml

